# Generated by Django 4.2.10 on 2024-03-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="class",
            old_name="cla_name",
            new_name="class_name",
        ),
    ]
